// DO NOT EDIT THIS FILE
// This file is automatically generated from the webgme-setup-tool.
'use strict';


var config = require('webgme/config/config.default'),
    validateConfig = require('webgme/config/validator');

// The paths can be loaded from the webgme-setup.json
config.seedProjects.basePaths.push(__dirname + '/../src/seeds/TicTacToe');







// Visualizer descriptors

// Add requirejs paths
config.requirejsPaths = {
  'mic-react-viz': './src/common'
};


config.mongo.uri = 'mongodb://127.0.0.1:27017/mic_react_viz';
validateConfig(config);
module.exports = config;
